version: '3.8'
services:
  api:
    build: .
    container_name: dy-express-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - mongodb  # 表示依赖MongoDB服务（仅用于启动顺序）
    networks:
      - app-network  # 加入同一个共享网络
networks:
  app-network:
    external: true  # 使用相同的外部共享网络

# 声明对MongoDB服务的依赖（仅用于Compose的启动顺序控制）
volumes:
  node_modules:
