version: '3.8'
services:
  api:
    build: .
    container_name: dy-express-api
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai  # 强制覆盖时区环境变量
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    networks:
      - app-network  # 加入同一个共享网络
networks:
  app-network:
    external: true  # 使用相同的外部共享网络

volumes:
  node_modules:
